### PR TITLE
fix: Name `f"server.modules.user.accessright.{right}"` correctly

### PR DESCRIPTION
**Pull request by ArneGudermann**
Fix for: https://github.com/viur-framework/viur-core/issues/1035 and Replacement for #1315

### CODE REVIEW

**Review by sveneberth — CHANGES_REQUESTED** [review]
I would this name `viur.core.*` since ViUR is ecosystem and has several components

**Comment by ArneGudermann** [comment]
> I would name this `viur.core.*` since ViUR is ecosystem and has several components

I have taken an example from https://github.com/search?q=repo%3Aviur-framework%2Fviur-core%20%20viur.modules.user&type=code

**Comment by phorward** [comment]
@ArneGudermann @sveneberth how important is this now? Is it a required feature? Is it really necessary for 3.6? Please agree.

**Comment by sveneberth** [comment]
> @ArneGudermann @sveneberth how important is this now? Is it a required feature? Is it really necessary for 3.6? Please agree.

No, not necessary for me, neither in 3.6 nor in 3.7. And I don't care what we call it. 

@ArneGudermann simply works only on prio low tickets ...

**Review by phorward — APPROVED** [review]

**Pull request merged**
