### PR TITLE
fix: Add check for `callable` in `BooleanBone`

### PR DESCRIPTION
**Pull request by ArneGudermann**
Fix for #1178

### CODE REVIEW

**Review by sveneberth — CHANGES_REQUESTED** [review]
That's not really useful. A callable `defaultValue` should be called at runtime: https://github.com/viur-framework/viur-core/blob/40d4e8228e72110c69d86ed80e680a55efc64656/src/viur/core/bones/base.py#L358

otherwise I could `BooleanBone(defaultValue=my_func())` directly ...

**Comment by ArneGudermann** [comment]
Yes, you are right. The whole thing with the default value needs to be revised... . I don't know if we should wait for #1154. Or is it enough to allow callables for now?

**Review by phorward — DISMISSED** [review]

**Comment by sveneberth** [comment]
> Yes, you are right. The whole thing with the default value needs to be revised... . I don't know if we should wait for #1154. Or is it enough to allow callables for now?

Is okay

```py
my_bone = BooleanBone(...)
my_bone.defaultValue = lambda skel, bone: ...
```
does the job for now too

**Comment by phorward** [comment]
Ok,what's with this PR now? It's still flagged for ViUR-core 3.6. Can we close it?

**Comment by sveneberth** [comment]
> Ok,what's with this PR now? It's still flagged for ViUR-core 3.6. Can we close it?

As it's not really solving the problem and it's possible to workaround with a monkey patch I would recommend to close this too and wait for 3.7.

**Pull request closed without merging**
