### PR TITLE
Add JsonBone for the user to store config information.

### PR DESCRIPTION
**Pull request by ArneGudermann**
This PR adds `admin_config` to the UserSkel to store configrations. In the new VI we want to store infos about the favorite modules of a user and now we can store it in a `JsonBone`

### CODE REVIEW

**Comment by phorward** [comment]
> In the new VI we want to store infos about the favorite modules of a user and now we can store it in a `JsonBone`

Hello @ArneGudermann, can you shortly explain why this can't be solved using a `RecordBone` with a defined structure? IMHO a JsonBone is not a good choice here, as it can save arbitrarily expressed information, which might gets corrupted on bugs or when different versions of the VI are writing broken data.

**Comment by ArneGudermann** [comment]
I chose a JsonBone here because at this point we don't know what all we want to store. For example, a history can still be added. Of course you could always extend the structure but then the VI must always wait for the core.

**Review by sveneberth — CHANGES_REQUESTED** [review]
Would be okay for me, if this is clearly in the responsibility of the client. But please add a comment or (not exclusive) a tooltip to the bone (sth. like: _"This bone stores settings from the vi"_). Furthermore I think this could be `visible=False`, what do you think?

**Review by phorward — APPROVED** [review]

**Review by sveneberth — APPROVED** [review]

**Comment by phorward** [comment]
We should think about #653 for this as well.

**Pull request merged**
