### PR TITLE
fix: `SelectBone.singleValueFromClient` doesn't accept `Enum` (backport #1320)

### PR DESCRIPTION
**Pull request by ArneGudermann**
Fix for : #1348

### CODE REVIEW

**Review by phorward — CHANGES_REQUESTED** [review]
Hi, this problem has already been resolved by #1320 and additionally hotfixed by https://github.com/viur-framework/viur-core/commit/47d630bba8d0dc2aa11a9563264aa292d8960fde. I would like to downport the entire function from 3.7 to 3.6.

**Comment by phorward** [comment]
@ArneGudermann this is my proposal does @sveneberth comply?

**Comment by ArneGudermann** [comment]
Im fine with this.

**Comment by sveneberth** [comment]
> @ArneGudermann this is my proposal does @sveneberth comply?

okay for me too

**Review by phorward — APPROVED** [review]

**Pull request merged**
