### PR TITLE
feat: Re-add `unescape_string`-function

### PR DESCRIPTION
**Pull request by ArneGudermann**

### CODE REVIEW

**Review by phorward — DISMISSED** [review]
Yay! Finally, this function is re-added again, after it was [mysteriously removed a few years ago for very important and perfectly understandable reasons](https://github.com/viur-framework/viur-core/commit/438fd45a54acc078d10ecfcf27451ed259b98f44)............................................................................................................................................................................................................................................................................................................................................................................

**Comment by phorward** [comment]
> I'm not sure, why we need this `max_length` part here in this method too?

@ArneGudermann this function is a utility-function not used in viur-core yet. Therefore, it is a valid question.

**Comment by ArneGudermann** [comment]
I wanted it to be an exact counterpart of the `unescape_string` function. But I can also just take it out

**Comment by phorward** [comment]
> I wanted it to be an exact counterpart of the `unescape_string` function. But I can also just take it out. Or should we just set the default limit to unlimeted?

no, the question is, is it useful?

**Comment by ArneGudermann** [comment]
I don't have an useful expample for it now.

**Comment by sveneberth** [comment]
> Or should we just set the default limit to unlimeted?

I would definitely find that much better.

---

And then I no longer really see the advantage in writing
```py
unescape_string(value, 128)
```
instead of
```py
unescape_string(value)[:128]
```

---

I would simply remove it. The string length will never increase with this method — in contrast to the escape method.

**Comment by phorward** [comment]
#992 is a replacement for this PR

**Comment by phorward** [comment]
Replaced by #992

**Pull request closed without merging**
