### PR TITLE
perf: Load session only when requested

### PR DESCRIPTION
**Pull request by ArneGudermann**
This PR should improve session loading. Currently the session is loaded on every request even if not necessary. With this PR we now only load the session if needed. Like getting the current user and so on

### CODE REVIEW

**Review by sveneberth — COMMENTED** [review]
Hey @ArneGudermann, I like the idea, but I'm not happy with the implementation yet. But I don't have an ad hoc alternative suggestion either. I'll have to take another look at it. It might be necessary to start somewhere else.

I don't like the multiple `if not self.loaded: self.load()` lines in the `session` module.

And I find this swapping of the `CurrentUser` instance with the `ContextVar` very hacky. 
[In the documentation, it is advised to create ContextVars only at top module level.](https://docs.python.org/3/library/contextvars.html#:~:text=Important%3A%20Context%20Variables%20should%20be%20created%20at%20the%20top%20module%20level)

**Comment by phorward** [comment]
We should give it another try in viur-core 3.8 @ArneGudermann ?

**Comment by phorward** [comment]
@ArneGudermann was this now replaced by #1277, I think so?

**Comment by phorward** [comment]
Closed as this was replaced by #1277.

**Pull request closed without merging**
