### PR TITLE
Fixed retreiving skeleton structure via view/structure

### LINKED ISSUE #207: /{module}/view/structure is broken in json/vi renderer
The requests ends in a the 401 Unauthorized.

The problem is the `canView`-method. The passing skeleton is empty/clean. Therefor `skel["key"]` is `None` and is declared as invalid in _buildDBFilter_ of the _KeyBone_ (called from `mergeExternalFilter`).

```sh
ERROR    2021-02-26 18:30:59,117 keyBone.py:100] None could not be converted to bytes
Traceback (most recent call last):
  File "/.../deploy/viur/core/bones/keyBone.py", line 98, in _decodeKey
    return KeyClass.from_legacy_urlsafe(key)
  File "/tmp/tmpfc49Z1/lib/python3.9/site-packages/google/cloud/datastore/key.py", line 356, in from_legacy_urlsafe
    urlsafe = _to_bytes(urlsafe, encoding="ascii")
  File "/tmp/tmpfc49Z1/lib/python3.9/site-packages/google/cloud/_helpers.py", line 370, in _to_bytes
    raise TypeError("%r could not be converted to bytes" % (value,))
TypeError: None could not be converted to bytes
WARNING  2021-02-26 18:30:59,120 keyBone.py:101] Could not decode key None
ERROR    2021-02-26 18:30:59,120 db.py:326] 
Traceback (most recent call last):
  File "/.../deploy/viur/core/bones/keyBone.py", line 98, in _decodeKey
    return KeyClass.from_legacy_urlsafe(key)
  File "/tmp/tmpfc49Z1/lib/python3.9/site-packages/google/cloud/datastore/key.py", line 356, in from_legacy_urlsafe
    urlsafe = _to_bytes(urlsafe, encoding="ascii")
  File "/tmp/tmpfc49Z1/lib/python3.9/site-packages/google/cloud/_helpers.py", line 370, in _to_bytes
    raise TypeError("%r could not be converted to bytes" % (value,))
TypeError: None could not be converted to bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../deploy/viur/core/bones/keyBone.py", line 124, in buildDBFilter
    dbFilter.filter("%s%s =" % (prefix or "", KEY_SPECIAL_PROPERTY), _decodeKey(rawFilter[name]))
  File "/.../deploy/viur/core/bones/keyBone.py", line 102, in _decodeKey
    raise RuntimeError()
RuntimeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../deploy/viur/core/db.py", line 321, in mergeExternalFilter
    bone.buildDBFilter(key, skel, self, filters)
  File "/.../deploy/viur/core/bones/keyBone.py", line 128, in buildDBFilter
    raise RuntimeError()
RuntimeError

```

### PR DESCRIPTION
**Pull request by tsteinruecken**
Fixes #207

### CODE REVIEW

**Review by sveneberth — CHANGES_REQUESTED** [review]
I don't think this is a good solution.
This means that if you want to get the structure efficiently in the future, you can no longer do this when the kind is empty. So you can't fetch the structure anymore to create your first entry. Especially in view of the fact that we have already considered getting rid of the structure overhead, this is conflicting.

**Comment by tsteinruecken** [comment]
That's consistent behavior. You don't get the structure in json/module/list requests either if there are no entities to return.
You still can add entities, as calling /add will also provide the skeleton structure. The only thing we could do is calling canAdd() and return the structure (despite an empty kind) if the user is allowed to add entities. But that would kinda mix canView/canAdd permissions...

**Review by phorward — CHANGES_REQUESTED** [review]
We talked about it in today's ViUR meeting and should replace this by a separate function.

**Comment by tsteinruecken** [comment]
Replaced by #223

**Pull request closed without merging**
