### PR TITLE
feat: Extend DateBone to allow for time  with microseconds

### PR DESCRIPTION
**Pull request by ArneGudermann**
Resolves : #790

### CODE REVIEW

**Review by phorward — CHANGES_REQUESTED** [review]
Hello @ArneGudermann, thanks for working on this!

I'm a little unhappy with the naming convention of the new configuration. `allow_microsecond` is only an additional configuration of the `time=True` case, therefore it should only be allowed in combination with `time=True`. This could be done with an Enum, for example, so `time=True` becomes a backward compatibility only. 

Let's think further about it.... why might time=True not always store microseconds, as the information is there, and microsecond is just set 0 when not provided (e.g. in old-style VI date-time-formattings `dd.mm.yyyy hh:mm:ss`.

Or, maybe split `DateBone` into `DateBone`, `TimeBone` and `DateTimeBone`? 

Let's discuss about this next Friday.

**Comment by sveneberth** [comment]
> Or, maybe split `DateBone` into `DateBone`, `TimeBone` and `DateTimeBone`?

that sounds like proven concepts, as in SQL.

---

By the way, I also have a use case for a (computable) `TimeDeltaBone` :)

**Comment by phorward** [comment]
> By the way, I also have a use case for a (computable) `TimeDeltaBone` :)

Hahah, I've created a `DeltaBone` in a customer's project, decades ago.. that's exactly this thing.

**Comment by phorward** [comment]
In the viur-meeting from Dec 8, 2023, we decided to resolve this issue differently, and split the `DateBone` into several bones:

- `DateBone` - used for dates
- `TimeBone` - used for times
- `DateTimeBone(microseconds=True)` - used for date and time
- `DeltaBone` - used for durations

This requires more investigation and work, may be part of viur-core > 3.6.

**Pull request closed without merging**
