### PR TITLE
Revert to old server-behavior: bones are not indexed by default

### PR DESCRIPTION
**Pull request by sveneberth**

### CODE REVIEW

**Review by xnopasaranx — APPROVED** [review]

**Comment by xnopasaranx** [comment]
this should be the other way around by default in my opinion. otherwise people will definitely forget to set indexed=False on bones and cause massive writeops

**Comment by tsteinruecken** [comment]
I would suggest keeping the default indexed (but set textbones to not indexed to avoid issues with text longer than 1,5kb). There is no additional cost involved using more indexed fields - and i've not seen an increased write latency anymore. On the other hand we have often issues with queries failing due to fields not being indexed.

**Review by phorward — APPROVED** [review]

**Comment by tsteinruecken** [comment]
As discussed, we'll keep the new indexed=True default behavior and just set it on textbones to false

**Comment by sveneberth** [comment]
> As discussed, we'll keep the new indexed=True default behavior and just set it on textbones to false

It would have been nice if you had provided an alternative PR than just closing that.

**Pull request closed without merging**
